#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/xfinity/xfinity /usr/bin/xfinity
	
	if [ "systemd" == "$INITSYS" ]; then
 		# Remove any conflicting service files
        if [ -e /etc/systemd/system/xfinity.service ]; then
            /bin/rm -f /etc/systemd/system/xfinity.service /usr/lib/systemd/system/xfinity.service /usr/lib/systemd/user/xfinity.service >/dev/null 2>&1
        fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
        cp /usr/share/xfinity/files/systemd/xfinity.service /usr/lib/systemd/system/xfinity.service

		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
        if [ -e /usr/bin/pkill ]; then
            /bin/sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/xfinity.service
        fi

        systemctl daemon-reload
        systemctl enable xfinity
        systemctl start xfinity || {
            echo "Failed to start xfinity service"
            exit 1
        }
	fi
fi
